from encodings import utf_8
from utils.AESED import *
from rsa_main import *
import os

# Confidentiality
# Sender
def sendM(message, digitalSign):
    print("==========================================")
    print("Confidentiality Checking")
    #1) The sender generates a random128-bit (16 bytes) number to be used as SSSK
    sssk = os.urandom (16)
    #2) The sender encrypts the clear-text message, and appended digital signature,using a symmetric encryption algorithm (AES) with the SSSK
    # message = bytes(message, 'utf-8')
    # plaintext = message + digitalSign
    aesE = AESE(message,sssk)
    # key,plaintext = sha1E
    sssks = str(sssk)
    # print(sha1E)
    #3) Encrypt the SSSK using RSA with each recipient’s public key(s) & append each uniquely encrypted copy of the SSSK to the black-text message
    cipher = RSAEpu(sssks,Receiver)
    # print(cipher)
    return(receiveM(cipher,aesE,message,sssk))

#Receiver
#4) Decrypt the RSA encryptes SHA-1 message digest using senders private key (RSA)
#5) The receiver decodes the SHA-1 message digest and matches it with the one generated by the sender
def receiveM(cipher,aesE,plaintext,sssk):
    decrypted = RSADpr(cipher,Receiver)
    # print(decrypted)
    # print(sssk)
    if decrypted == str(sssk):
        message = AESD(aesE,sssk)
        print("Email Integrity Maintained")
        print("Confidentialty Check Completed ")
        print("==========================================")
        print("Email Sent and Received Successfully")
        message = str(message)[2:-1]
        return(message)  
    else:
        print("Email Integrity not maintained")
        return("Email has been tampered")
    

# sent = sendM("Hi i am tandin", "3cd013da8e848fc2bab3d805ed9df6b1f006d0fd")
# print(sent)